version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: ${AZURE_HOST}
      MYSQL_USER: ${AZURE_UN}
      MYSQL_PASSWORD: ${AZURE_PW}
      MYSQL_DATABASE: ${AZURE_DB}
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ACRRS14!
      MYSQL_DATABASE: ibm
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
