name: "Rspec tests"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Rspec Tests

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.AZURE_PW }}
          MYSQL_USER: ${{ secrets.AZURE_UN }}
          MYSQL_PASSWORD: ${{ secrets.AZURE_PW }}
          MYSQL_DATABASE: test
          MYSQL_HOST: ${{ secrets.AZURE_HOST }}
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Configure database.yml
        run: |
          cp config/database.yml.example config/database.yml
          sed -i "s|username: .*|username: ${{ secrets.AZURE_UN }}|" config/database.yml
          sed -i "s|password: .*|password: ${{ secrets.AZURE_PW }}|" config/database.yml
          sed -i "s|host: .*|host: ${{ secrets.AZURE_HOST }}|" config/database.yml

      - name: "Authentication spec"
        run: bundle exec rspec ./spec/requests/authentication_spec.rb