name: "Rspec tests"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
    test:
        runs-on: ubuntu-latest
        name: Run Rspec Tests
        services:
          mysql:
            image: mysql:5.7
            env:
              AZURE_HOST: ${{secrets.AZURE_HOST}}
              AZURE_UN: ${{secrets.AZURE_UN}}
              AZURE_PW: ${{secrets.AZURE_PW}}
              AZURE_DB: test
            ports:
              - "3306:3306"
        env:
          RAILS_ENV: test
          MYSQL_ROOT_PASSWORD: ${{secrets.AZURE_PW}}
          MYSQL_DATABASE: test

        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v1

            - name: "Setup ruby"
              uses: ruby/setup-ruby@v1
              with:
                ruby-version: '3.2.2'
                bundler-cache: true

            - name: "Start MySQL service"
              run: sudo service mysql start
                
            - name: "Authentication spec"
              run: bundle exec rspec ./spec/requests/authentication_spec.rb
